print("========================================")
print("          INFORMACIÓN PERSONAL          ")
print("========================================")
print("Nombre completo: Gustavo Hernández García")
print("Fortalezas: Responsabilidad, empatia y humildad")
print("Debilidades: Perfeccionismo y desconfianza")
print("----------------------------------------")
print("GUSTOS Y ACTIVIDADES")
print("----------------------------------------")
print("Gustos musicales: Rap y Rock Mexicano")
print("Artistas fav: C-Kan, Cartel de Santa, Molotov, el tri, haragan y compania, inspector")
print("Actividades de vacaciones: Trabajar y cuidar animales")
print("----------------------------------------")

print("----------------------------------------")
print("Estado de ánimo: Alegre")
print("----------------------------------------")
print("Autor del archivo: Gustavo Hernández García")
print("========================================")